### PR TITLE
Beta Release 2

### PR DESCRIPTION
**Pull request by Rahkeen**
This update includes adding new feeds as well as fixing a crash on startup.

### CODE REVIEW

**Comment by Rahkeen** [comment]
* **#117** <a href="https://app.graphite.dev/github/pr/EmergeTools/hackernews/117?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Rahkeen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Rahkeen** [comment]
Bumped the version number a few times, generated a couple builds 😅

**Review by rbro112 — APPROVED** [review]
Assuming this is just formality since the beta02 was already published?

**Comment by Rahkeen** [comment]
Yep exactly, will iron out the release process a bit though.

**Comment by Rahkeen** [comment]
### Merge activity

* **Aug 15, 1:16 AM EDT**: @Rahkeen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/EmergeTools/hackernews/117).

**Pull request merged**
